# Site settings
title: MiniTitan Web Comics
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  MiniTitan Web Comics, for some of your comic needs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  LilR
tumblr_username: Lily-Likes-Tea

# Build settings
markdown: kramdown
